import './globals.css';
import { Press_Start_2P } from 'next/font/google';

const pixelFont = Press_Start_2P({ 
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'te amo',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head>
        <link href="https://fonts.cdnfonts.com/css/minecraft-4" rel="stylesheet" />
      </head>
      <body style={{ fontFamily: 'Minecraft, monospace' }}>
        {children}
      </body>
    </html>
  )
}